import axios from 'axios';

const getAuthHeader = () => {
    const token = localStorage.getItem("skillforge_token");
    return {
        headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json"
        }
    };
};

export const aiService = {
    async generateQuestions(params) {
        const { questionType, numQuestions, numMcq, numLong, topicName, difficulty } = params;

        let payload;

        if (questionType === 'MIXED') {
            payload = {
                topicName,
                difficulty,
                numMcqQuestions: numMcq || 3,
                numLongQuestions: numLong || 2,
                questionType: 'MIXED',
                numQuestions: (numMcq || 3) + (numLong || 2)
            };
        } else {
            payload = {
                topicName,
                difficulty,
                numQuestions: numQuestions || 5,
                questionType: questionType || 'MCQ',
                numMcqQuestions: questionType === 'MCQ' ? (numQuestions || 5) : 0,
                numLongQuestions: questionType === 'LONG' ? (numQuestions || 5) : 0
            };
        }

        console.log('🚀 AI Service - Sending payload:', payload);

        try {
            const response = await axios.post(
                'http://localhost:8081/api/ai/generate-quiz',
                payload,
                getAuthHeader()
            );

            console.log('✅ AI Service - Raw response:', response);
            console.log('📋 AI Service - Response data:', response.data);

            const questions = response.data || [];

            // Transform backend format to frontend format
            const transformedQuestions = questions.map((q, index) => {
                const questionType = (q.type || 'MCQ').toUpperCase();

                if (questionType === 'MCQ') {
                    return {
                        questionId: q.questionId || (index + 1).toString(),
                        question: q.question || q.questionText || '',
                        type: 'MCQ',
                        optionA: q.optionA || '',
                        optionB: q.optionB || '',
                        optionC: q.optionC || '',
                        optionD: q.optionD || '',
                        correctAnswer: q.correctAnswer || 'A'
                    };
                } else {
                    return {
                        questionId: q.questionId || (index + 1).toString(),
                        question: q.question || q.questionText || '',
                        type: questionType,
                        optionA: null,
                        optionB: null,
                        optionC: null,
                        optionD: null,
                        correctAnswer: q.correctAnswer || ''
                    };
                }
            });

            console.log('🔄 AI Service - Transformed questions:', transformedQuestions);

            if (transformedQuestions.length === 0) {
                throw new Error('No questions were generated by the AI service');
            }

            // Check if we got real AI questions or fallback samples
            const hasRealQuestions = transformedQuestions.some(q =>
                q.question && !q.question.toLowerCase().includes('sample')
            );

            if (!hasRealQuestions) {
                console.warn('⚠️ Received sample questions instead of AI-generated content');
            }

            return transformedQuestions;

        } catch (error) {
            console.error('❌ AI Service - Request failed:', error);
            console.error('❌ Error details:', {
                message: error.message,
                status: error.response?.status,
                statusText: error.response?.statusText,
                data: error.response?.data
            });

            // Re-throw with more context
            throw new Error(`AI generation failed: ${error.response?.data?.message || error.message}`);
        }
    },

    async saveAiQuiz(quizData) {
        console.log('💾 AI Service - Saving quiz:', quizData);
        try {
            const response = await axios.post(
                'http://localhost:8081/api/instructor/quiz/ai-create',
                quizData,
                getAuthHeader()
            );
            console.log('✅ AI Service - Quiz saved successfully:', response.data);
            return response.data;
        } catch (error) {
            console.error('❌ AI Service - Save failed:', error);
            throw new Error(`Failed to save AI quiz: ${error.response?.data?.message || error.message}`);
        }
    },

    async generateStudySuggestions(params) {
        try {
            const response = await axios.post(
                'http://localhost:8081/api/ai/study-suggestions',
                params,
                getAuthHeader()
            );
            return response.data;
        } catch (error) {
            console.error('❌ AI Service - Study suggestions failed:', error);
            return "Keep practicing! Review your notes and focus on the areas where you missed marks. You've got this!";
        }
    }
};